// <auto-generated />
using System;
using KurumsalEgitimSitesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KurumsalEgitimSitesi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218194922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KurumsalEgitimSitesi.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Announcements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Kurumsal Eğitim",
                            Content = "2025 yılı için hazırladığımız kapsamlı eğitim kataloğumuz yayına alınmıştır. Kamu kurumları ve özel sektör için özel olarak tasarlanmış programlarımızı inceleyebilirsiniz.",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Yeni dönem eğitim programlarımız açıklandı.",
                            Title = "2025 Yılı Eğitim Kataloğumuz Yayında!",
                            Type = "Duyuru"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Kurumsal Eğitim",
                            Content = "2025 yaz dönemi Antalya seminer programımız açıklanmıştır. Sınırlı kontenjanlarımız hızla dolmaktadır. Detaylı bilgi ve kayıt için bizimle iletişime geçebilirsiniz.",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "2025 yaz dönemi Antalya seminerleri başlıyor.",
                            Title = "Antalya Seminer Programı Açıklandı",
                            Type = "Duyuru"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Dr. Ahmet Yılmaz",
                            Content = "Dijital dönüşüm sürecinde kurumların en büyük yatırımı insan kaynağına yapılmalıdır. Bu yazımızda dijital dönüşümde kurumsal eğitimin rolünü ve önemini ele alıyoruz.",
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Dijital çağda kurumsal eğitim neden kritik?",
                            Title = "Dijital Dönüşümde Kurumsal Eğitimin Önemi",
                            Type = "Blog"
                        });
                });

            modelBuilder.Entity("KurumsalEgitimSitesi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#f97316",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çalışanlarınızın kişisel ve profesyonel gelişimini destekleyen eğitim programları.",
                            IconClass = "fas fa-user-graduate",
                            IsActive = true,
                            Name = "Kişisel Gelişim",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#2563eb",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dijital dönüşüm süreçlerinizi destekleyen güncel teknoloji eğitimleri.",
                            IconClass = "fas fa-laptop-code",
                            IsActive = true,
                            Name = "Teknoloji",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#dc2626",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kurumunuzun bilgi güvenliğini sağlamak için kritik siber güvenlik eğitimleri.",
                            IconClass = "fas fa-shield-alt",
                            IsActive = true,
                            Name = "Siber Güvenlik",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#059669",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İş verimliliğinizi artıracak Microsoft Office uygulamaları eğitimleri.",
                            IconClass = "fab fa-microsoft",
                            IsActive = true,
                            Name = "MS Office",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#7c3aed",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Resmi protokol kuralları ve kurumsal temsil becerilerini geliştiren eğitimler.",
                            IconClass = "fas fa-handshake",
                            IsActive = true,
                            Name = "Protokol ve Teşrifat",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#0891b2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kamu personeline özel tasarlanmış hizmet içi eğitim programları.",
                            IconClass = "fas fa-landmark",
                            IsActive = true,
                            Name = "Kamu Kurumları",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "#ea580c",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kişisel Verilerin Korunması Kanunu kapsamında zorunlu farkındalık ve uyum eğitimleri.",
                            IconClass = "fas fa-user-lock",
                            IsActive = true,
                            Name = "KVKK",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("KurumsalEgitimSitesi.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLimitedCapacity")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kamu ihale mevzuatındaki güncel değişiklikler ve uygulamalar.",
                            EndDate = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "Seminer",
                            IsActive = true,
                            IsLimitedCapacity = true,
                            Location = "Kundu Deluxe Otel, Antalya",
                            StartDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "İhale Uygulamaları ve Güncel Mevzuat Eğitimi"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Belediye mevzuatı ve denetim süreçleri hakkında kapsamlı eğitim.",
                            EndDate = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "Seminer",
                            IsActive = true,
                            IsLimitedCapacity = true,
                            Location = "Luxury Resort & Spa, Antalya",
                            StartDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Belediyeler için Mevzuat ve Denetim Eğitimi"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 45,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İhale süreçleri ve mevzuat uygulamaları.",
                            EndDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "Seminer",
                            IsActive = true,
                            IsLimitedCapacity = true,
                            Location = "Paradise Kundu Otel, Antalya",
                            StartDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Kamu İhale Mevzuatı ve Uygulamaları Eğitimi"
                        });
                });

            modelBuilder.Entity("KurumsalEgitimSitesi.Models.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IconColorClass")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Sector")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("References", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "T.C. Gümrük Müsteşarlığı",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Liderlik ve İletişim Eğitimleri",
                            IconClass = "fas fa-landmark",
                            IconColorClass = "red",
                            IsActive = true,
                            Sector = "Kamu",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "İstanbul Büyükşehir Belediyesi",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mevzuat ve Denetim Eğitimleri",
                            IconClass = "fas fa-university",
                            IconColorClass = "blue",
                            IsActive = true,
                            Sector = "Kamu",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Arçelik",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İhale Danışmanlığı ve Eğitim Programları",
                            IconClass = "fas fa-industry",
                            IconColorClass = "orange",
                            IsActive = true,
                            Sector = "Özel Sektör",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Naile Danışmanlık",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kurumsal Danışmanlık ve Eğitim",
                            IconClass = "fas fa-handshake",
                            IconColorClass = "red",
                            IsActive = true,
                            Sector = "Özel Sektör",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("KurumsalEgitimSitesi.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CertificateType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Trainings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Etkili liderlik becerileri, ekip yönetimi, motivasyon teknikleri ve stratejik düşünme konularını kapsayan kapsamlı eğitim programı.",
                            Duration = "2 Gün (16 Saat)",
                            IsActive = true,
                            IsFeatured = true,
                            Level = "İleri",
                            ShortDescription = "Etkili liderlik becerileri ve ekip yönetimi.",
                            SortOrder = 1,
                            TargetAudience = "Orta ve Üst Düzey Yöneticiler",
                            Title = "Liderlik ve Yöneticilik"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sözlü ve yazılı iletişim, aktif dinleme, empati, beden dili ve profesyonel iletişim teknikleri eğitimi.",
                            Duration = "1 Gün (8 Saat)",
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Temel",
                            ShortDescription = "Sözlü ve yazılı iletişim teknikleri.",
                            SortOrder = 2,
                            TargetAudience = "Tüm Çalışanlar",
                            Title = "Etkili İletişim Becerileri"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Önceliklendirme, planlama teknikleri, stres kaynaklarını tanıma ve başa çıkma stratejileri.",
                            Duration = "1 Gün (8 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Temel",
                            ShortDescription = "Önceliklendirme ve stresle başa çıkma.",
                            SortOrder = 3,
                            TargetAudience = "Tüm Çalışanlar",
                            Title = "Zaman ve Stres Yönetimi"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dijital çağda iş süreçleri, teknoloji trendleri ve kurumlarda dijital dönüşüm stratejileri.",
                            Duration = "1 Gün (8 Saat)",
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Temel",
                            ShortDescription = "Dijital çağda iş süreçleri ve teknoloji trendleri.",
                            SortOrder = 1,
                            TargetAudience = "Tüm Çalışanlar",
                            Title = "Dijital Dönüşüm Farkındalık"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Veri toplama, analiz yöntemleri, raporlama teknikleri ve veri odaklı karar verme süreçleri.",
                            Duration = "2 Gün (16 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Orta",
                            ShortDescription = "Veri toplama, analiz ve raporlama.",
                            SortOrder = 2,
                            TargetAudience = "Veri ile Çalışan Personel",
                            Title = "Veri Analitiği Temelleri"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sosyal mühendislik saldırıları, phishing, güvenli parola kullanımı ve temel güvenlik önlemleri.",
                            Duration = "1 Gün (8 Saat)",
                            IsActive = true,
                            IsFeatured = true,
                            Level = "Temel",
                            ShortDescription = "Temel güvenlik önlemleri ve farkındalık.",
                            SortOrder = 1,
                            TargetAudience = "Tüm Çalışanlar",
                            Title = "Siber Güvenlik Farkındalık"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ISO 27001, güvenlik politikaları, risk yönetimi ve olay müdahale süreçleri.",
                            Duration = "2 Gün (16 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "İleri",
                            ShortDescription = "ISO 27001 ve güvenlik politikaları.",
                            SortOrder = 2,
                            TargetAudience = "IT ve Güvenlik Personeli",
                            Title = "Kurumsal Bilgi Güvenliği"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pivot tablolar, makrolar, ileri formüller, veri analizi ve dashboard oluşturma teknikleri.",
                            Duration = "2 Gün (16 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "İleri",
                            ShortDescription = "Pivot tablolar, makrolar ve ileri formüller.",
                            SortOrder = 1,
                            TargetAudience = "Veri ile Çalışan Personel",
                            Title = "Excel İleri Seviye"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profesyonel sunum tasarımı, animasyon teknikleri ve etkili sunum becerileri.",
                            Duration = "1 Gün (8 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Orta",
                            ShortDescription = "Profesyonel sunum tasarımı.",
                            SortOrder = 2,
                            TargetAudience = "Sunum Yapan Personel",
                            Title = "PowerPoint Profesyonel"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Devlet protokolü, masa düzeni, tören yönetimi, diplomatik nezaket kuralları.",
                            Duration = "2 Gün (16 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Orta",
                            ShortDescription = "Devlet protokolü ve tören yönetimi.",
                            SortOrder = 1,
                            TargetAudience = "Kamu Personeli, Protokol Görevlileri",
                            Title = "Resmi Protokol Kuralları"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profesyonel görünüm, davranış standartları, kurumsal imaj yönetimi.",
                            Duration = "1 Gün (8 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Temel",
                            ShortDescription = "Profesyonel görünüm ve davranış standartları.",
                            SortOrder = 2,
                            TargetAudience = "Tüm Çalışanlar",
                            Title = "Kurumsal Temsil ve Davranış"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CertificateType = "Hizmet İçi Eğitim Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kamu kurumlarının ihtiyaçlarına özel tasarlanmış kapsamlı hizmet içi eğitimler.",
                            Duration = "Kuruma Özel",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Karma",
                            ShortDescription = "Kamu kurumlarına özel kapsamlı eğitimler.",
                            SortOrder = 1,
                            TargetAudience = "Kamu Personeli",
                            Title = "Hizmet İçi Eğitim Programı"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            CertificateType = "Katılım Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Güncel mevzuat değişiklikleri, yönetmelik uygulamaları ve yasal düzenlemeler.",
                            Duration = "1-2 Gün",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Orta",
                            ShortDescription = "Güncel mevzuat değişiklikleri ve uygulamaları.",
                            SortOrder = 2,
                            TargetAudience = "Kamu Personeli",
                            Title = "Mevzuat ve Yönetmelik Eğitimi"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            CertificateType = "KVKK Eğitim Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KVKK kapsamı, temel kavramlar, veri sorumlusu yükümlülükleri ve çalışan sorumlulukları.",
                            Duration = "1 Gün (8 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "Temel",
                            ShortDescription = "KVKK temel kavramlar ve çalışan sorumlulukları.",
                            SortOrder = 1,
                            TargetAudience = "Tüm Çalışanlar",
                            Title = "KVKK Farkındalık Eğitimi"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            CertificateType = "KVKK Uzman Sertifikası",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "VERBİS kaydı, politika hazırlama, veri envanteri, teknik ve idari tedbirler.",
                            Duration = "2 Gün (16 Saat)",
                            IsActive = true,
                            IsFeatured = false,
                            Level = "İleri",
                            ShortDescription = "VERBİS kaydı ve politika hazırlama.",
                            SortOrder = 2,
                            TargetAudience = "KVKK Sorumluları, IT Personeli",
                            Title = "KVKK Uyum Süreci"
                        });
                });

            modelBuilder.Entity("KurumsalEgitimSitesi.Models.Training", b =>
                {
                    b.HasOne("KurumsalEgitimSitesi.Models.Category", "Category")
                        .WithMany("Trainings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KurumsalEgitimSitesi.Models.Category", b =>
                {
                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
